# Generated by Django 5.2.3 on 2025-07-05 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('things', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Пользователь, который создал запись о вещи.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='things', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
