# Generated by Django 5.2.3 on 2025-07-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_phonenumberotp_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
