# Generated by Django 5.2.3 on 2025-07-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
